version: '3.8'

services:
  dev-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      DB_NAME: test
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - backend
networks:
  backend:
