version: '3'

services:
  dev-db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: nestjs-be-starter
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
